services:
  - docker

before_script:
  - docker login --username dylanderv --password ${DOCKERHUB_TOKEN}

script:
  - docker build -t dylanderv/drawio-cli .
  - docker push dylanderv/drawio-cli